language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x

services:
  - mysql
  - postgresql

install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/lib/pq

script:
  - test -z "$(go fmt ./...)" # fail if not formatted properly
  - go vet
  - make test # tests postgres and mysql databases
