language: go
go:
  - 1.3
  - 1.4
  - release
  - tip

services: mysql

install:
  # mysql database driver for tests
  - go get github.com/go-sql-driver/mysql

  # linters and vet
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint

script:
  # prepare database
  - make db

  # tests
  - go test -v
  - go test -race

  # code correctness, 1.2 version has different fmt version, skip it
  - sh -c 'RES="$(go fmt ./...)"; if [ ! -z "$RES" ]; then echo $RES; exit 1; fi'
  - sh -c 'RES="$(golint ./...)"; if [ ! -z "$RES" ]; then echo $RES; exit 1; fi'
  - go vet ./...
