version: "3"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: txdb_test
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: txdb_test
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 3306:3306
